name: job_studio_profile_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  badges: ^3.1.2
  barcode_widget: ^2.0.4
  file_picker: ^6.2.0
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.12.4
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_nav_bar: ^5.0.6
  pin_code_fields: ^8.0.1
  qr_flutter: ^4.1.0
  remixicon_updated: ^1.0.2
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  validators: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
